name: "Deploy"

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "index.html"
      - "package.json"
  pull_request:
    paths:
      - "src/**"
      - "index.html"
      - "package.json"
  workflow_dispatch:

permissions:
  contents: read
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test
        run: |
          npm install
          npm run test
  deploy:
    runs-on: ubuntu-20.04
    needs:
      - test
    environment:
      name: "production"
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
